//MD Abir A. Choudhury
//03/10/18
//Lab #2: Number Guessing Game

#include <iostream>
#include <cstdlib>
#include <ctime>

using namespace std;

int main()
{
	int num; // holding a random number generated by computer
	int guess; // holds the guess of the user
	int numTry = 0; //holds the number of times the user tried
	int difference = 0; // holds the difference between guess and num
	bool isGuessed; // true if user guessed the number correctly

	srand(time(0)); // initialize randomness with time
	num = rand() % 100; // ensure the number is 0 to 100

	isGuessed = false;

	cout << "I have a number between 0 and 100. Try to guess what it is." << endl << endl;

	cout << num;

	while (!isGuessed)
	{
		cout << "So, what is your guess? ";
		cin >> guess;

		if (guess == num)
		{
			numTry++;
			cout << "Phew... You got it!!" << endl << endl;
			cout << "You guessed this many times: " << numTry << endl;
			isGuessed = true;
		}
	
		if (numTry == 6)
		{
			cout << "You have lost the game. You did not guess in 6 tries.\n";
			break;
		}
	}

	system("PAUSE");
	return 0;
}